-- ==========================================================
-- Module 03 : GROUP BY & HAVING
-- Topic      : GROUP BY, HAVING, Aggregate Functions
-- Difficulty : Medium
-- Database   : TechMart
-- Questions  : 10
-- ==========================================================

-- Q1. Display the total number of customers in each status.
-- Expected Columns:
-- status | total_customers

-- Q2. Display the total number of products in each category.
-- Expected Columns:
-- category_id | total_products

-- Q3. Display the average selling price for each category.
-- Expected Columns:
-- category_id | average_price

-- Q4. Display the total revenue generated by each payment status.
-- Expected Columns:
-- payment_status | total_revenue

-- Q5. Display the total quantity sold for each product.
-- Expected Columns:
-- product_id | total_quantity

-- Q6. Display the total number of orders placed by each customer.
-- Expected Columns:
-- customer_id | total_orders

-- Q7. Display the average product rating for each product.
-- Expected Columns:
-- product_id | average_rating

-- Q8. Display the total number of suppliers in each state.
-- Expected Columns:
-- state | total_suppliers

-- Q9. Display categories having more than 100 products.
-- Use HAVING.
-- Expected Columns:
-- category_id | total_products

-- Q10. Display customers who have placed more than 5 orders.
-- Use HAVING.
-- Expected Columns:
-- customer_id | total_orders